'use strict';
// Canned answers the Decider can choose between (§1.2: the model picks, templates speak).
// Each entry: id, `about` (what the Decider reads), `keys` (phrases that shortlist it), answer text (<= 240 chars).

const KNOWLEDGE = Object.freeze([
  ['crafting_table', 'how to make and use a crafting table', ['crafting table', 'workbench', 'table', 'craft'],
    'A crafting table gives you a 3x3 crafting grid. Put 4 wood planks in your 2x2 inventory grid (E) to make one.'],
  ['pickaxe_tiers', 'which pickaxe mines which ore', ['pickaxe', 'pick', 'mine stone', 'tier', 'hathoda', 'which pickaxe'],
    'Wood mines stone and coal. Stone mines iron, copper and lapis. Iron mines gold, diamond, redstone and emerald. Diamond mines obsidian and ancient debris.'],
  ['night', 'surviving the night and monsters in the dark', ['night', 'dark', 'raat', 'monsters', 'survive', 'andhera'],
    'At night, hostile monsters (zombies, skeletons, creepers) spawn in the dark. Sleep in a bed or hide in a shelter until dawn.'],
  ['hunger', 'hunger, food and healing', ['hunger', 'hungry', 'food', 'khana', 'bhook', 'heal', 'health', 'regenerate'],
    'When hunger drops below 18, you stop healing. At 0, you take starvation damage. Hunt animals and cook the meat to restore it.'],
  ['bed', 'making a bed, sleeping and the respawn point', ['bed', 'sleep', 'bistar', 'spawn point', 'respawn point'],
    'Bed = 3 wool + 3 planks. Sleeping skips the night and sets your respawn point. You can\'t sleep with monsters nearby, and beds explode in the Nether!'],
  ['creeper', 'dealing with creepers', ['creeper', 'explode', 'explosion', 'hiss', 'blew up'],
    'Creepers hiss, then explode. Hit one and step back, block with a shield, or run. They are scared of cats. Lightning makes them charged and much stronger.'],
  ['skeleton', 'fighting skeletons and arrows', ['skeleton', 'arrow', 'shooting me', 'archer'],
    'Skeletons shoot arrows. Close in behind cover or a shield, or shoot back with a bow. Like zombies, they burn in sunlight.'],
  ['zombie', 'fighting zombies', ['zombie', 'zombies', 'undead'],
    'Zombies are slow and burn in daylight. A sword and some armor handle them. Watch out for baby zombies, they are fast!'],
  ['spider', 'spiders', ['spider', 'spiders', 'string'],
    'Spiders climb walls and are only hostile in the dark. They drop string (for bows and fishing rods) and spider eyes.'],
  ['enderman', 'endermen and ender pearls', ['enderman', 'endermen', 'ender pearl', 'tall black'],
    'Don\'t look an enderman in the eyes, it gets angry! Stand under a 2-block-high roof or next to water, they can\'t follow. They drop ender pearls.'],
  ['torch', 'making torches and lighting to stop mob spawns', ['torch', 'torches', 'light', 'roshni'],
    'Torch = 1 coal or charcoal on top of 1 stick, makes 4. Light stops monsters from spawning, so light up your base and caves.'],
  ['furnace', 'making and using a furnace, smelting and cooking', ['furnace', 'smelt', 'smelting', 'cook', 'bhatti'],
    'Furnace = 8 cobblestone in a ring at a crafting table. Put ore or raw food on top and fuel (coal, logs, planks) underneath.'],
  ['iron', 'finding and smelting iron', ['iron', 'raw iron', 'iron ore', 'loha'],
    'Iron ore is common in caves and mountains. Mine it with a stone pickaxe, then smelt the raw iron in a furnace to get ingots.'],
  ['diamond', 'finding diamonds', ['diamond', 'diamonds', 'heera'],
    'Diamonds are most common deep down, around y=-58. Bring an iron pickaxe, torches and food, then strip mine or explore deep caves. Watch for lava!'],
  ['coal', 'finding coal or charcoal', ['coal', 'charcoal', 'fuel', 'koyla'],
    'Coal ore is common in stone, especially in mountains and near the surface. Any pickaxe mines it. No coal? Smelt logs into charcoal.'],
  ['lava', 'lava safety', ['lava', 'burning', 'on fire', 'fire'],
    'Lava burns you and destroys dropped items. Pour water on still lava to turn it into obsidian. Carry a water bucket when you go deep.'],
  ['bucket', 'buckets and water tricks', ['bucket', 'water', 'fall damage', 'mlg', 'paani'],
    'Bucket = 3 iron ingots in a V. A water bucket stops fall damage if you place it just before landing, puts out fire and turns lava into obsidian.'],
  ['armor', 'armor sets and upgrades', ['armor', 'armour', 'helmet', 'chestplate', 'leggings', 'boots', 'protection'],
    'Armor takes 5 (helmet), 8 (chestplate), 7 (leggings) and 4 (boots) of one material. Iron is the first big upgrade, then diamond. Wear a full set before caving.'],
  ['shield', 'making and using a shield', ['shield', 'block', 'blocking', 'dhaal'],
    'Shield = 6 planks + 1 iron ingot. Hold right-click to block hits, arrows and even creeper blasts from the front.'],
  ['bow', 'making a bow and arrows', ['bow', 'arrows', 'archery', 'teer'],
    'Bow = 3 sticks + 3 string. Arrows = flint + stick + feather (makes 4). Hold right-click to charge; a full draw does the most damage.'],
  ['nether', 'building a nether portal and nether safety', ['nether', 'portal', 'hell', 'piglin', 'fortress'],
    'Nether portal: an obsidian frame at least 4 wide and 5 tall, lit with flint and steel. Wear gold armor so piglins stay calm, and bring blocks and food.'],
  ['obsidian', 'getting obsidian', ['obsidian'],
    'Obsidian forms when water touches still lava. Only a diamond or netherite pickaxe can mine it, and it takes a while.'],
  ['enchanting', 'enchanting tools and armor', ['enchant', 'enchanting', 'enchantment', 'bookshelf', 'lapis'],
    'Enchanting table = 4 obsidian + 2 diamonds + 1 book. Put up to 15 bookshelves around it, one block away, for level 30 enchants. It costs XP and lapis.'],
  ['villager', 'villagers and trading', ['villager', 'village', 'trade', 'trading', 'emerald', 'gaon'],
    'Villagers trade with emeralds. Their workstation block gives them their job. Keep them safe from zombies at night or they turn into zombie villagers.'],
  ['farming', 'farming crops like wheat, carrots and potatoes', ['farm', 'farming', 'crops', 'wheat', 'seeds', 'kheti', 'carrot', 'potato', 'bread'],
    'Till dirt with a hoe next to water and plant seeds from grass. 3 wheat make bread. Plant carrots and potatoes directly. Crops need light to grow.'],
  ['breeding', 'breeding animals', ['breed', 'breeding', 'baby animal', 'animal farm', 'cows', 'pigs', 'sheep'],
    'Feed two animals their favorite food to breed them: wheat for cows and sheep, carrots for pigs, seeds for chickens. Babies grow up in about 20 minutes.'],
  ['fishing', 'fishing', ['fish', 'fishing', 'fishing rod', 'machli'],
    'Fishing rod = 3 sticks + 2 string. Cast into water, wait for the bobber to dip, then reel in. You can catch fish, treasure and junk.'],
  ['death', 'what happens when you die and getting items back', ['die', 'died', 'death', 'dead', 'lost my items', 'mar gaya'],
    'When you die you drop your items and XP. They stay for 5 minutes before despawning. Say "helper get my stuff" and I\'ll fetch them!'],
  ['xp', 'experience points', ['xp', 'experience', 'levels', 'exp'],
    'You get XP from mining ores, killing mobs, smelting and breeding. Spend it on enchanting, or on repairs at an anvil.'],
  ['caving', 'cave exploring safety', ['cave', 'caves', 'caving', 'underground', 'gufa'],
    'Caving tips: light up everything, keep a water bucket, watch for lava, and put torches on one side only so you can find your way back.'],
  ['lost', 'finding your way when lost', ['lost', 'coordinates', 'compass', 'direction', 'kho gaya'],
    'Lost? Press F3 to see your coordinates. A compass (4 iron + 1 redstone) points to world spawn. Or ask me "helper where is home".'],
  ['boat', 'boats', ['boat', 'naav', 'river', 'ocean'],
    'Boat = 5 planks in a U shape. Boats are fast on water and ice, and mobs you push into one get stuck.'],
  ['horse', 'taming and riding horses', ['horse', 'ride', 'riding', 'saddle', 'ghoda'],
    'Tame a horse by getting on it again until hearts appear. You need a saddle (found in chests) to steer. Feed it apples or golden carrots.'],
  ['wolf', 'taming wolves as pets', ['wolf', 'dog', 'pet', 'kutta', 'bone'],
    'Tame wolves with bones. Tamed wolves follow you and fight mobs that attack you. Right-click to make them sit.'],
  ['cat', 'taming cats', ['cat', 'ocelot', 'billi', 'kitten'],
    'Tame cats with raw cod or salmon. Creepers run away from cats!'],
  ['potions', 'brewing potions', ['potion', 'potions', 'brew', 'brewing'],
    'Potions need a brewing stand (blaze rod + 3 cobblestone), water bottles and nether wart as the base. Blaze rods come from the Nether.'],
  ['redstone', 'redstone basics', ['redstone', 'circuit', 'piston', 'lever'],
    'Redstone works like wiring: dust carries power from levers, buttons and pressure plates to doors, pistons and lamps. Find it deep underground.'],
  ['end', 'reaching the End and fighting the Ender Dragon', ['end', 'ender dragon', 'dragon', 'stronghold', 'eye of ender'],
    'Throw eyes of ender (pearl + blaze powder) to find a stronghold, then fill its portal. The dragon heals from the crystals on the pillars: shoot those first!'],
  ['slime', 'slimes and slimeballs', ['slime', 'slimeball', 'swamp'],
    'Slimes spawn in swamps and in special slime chunks deep underground. Slimeballs make sticky pistons and leads.'],
  ['repair', 'repairing tools and anvils', ['repair', 'anvil', 'broken', 'durability', 'fix'],
    'Combine two worn tools of the same kind in a crafting grid, or use an anvil (3 iron blocks + 4 iron ingots) to repair without losing enchantments.'],
  ['chest', 'chests and storage', ['chest', 'storage', 'store', 'double chest', 'sandook'],
    'Chest = 8 planks in a ring. Two chests side by side make a double chest. I remember chests you place near you!'],
  ['house', 'building a first house', ['house', 'home', 'base', 'build', 'ghar', 'hut'],
    'A first house just needs walls, a roof, a door and torches inside. Want me to build one? Say "helper build a hut".'],
  ['phantom', 'phantoms', ['phantom', 'phantoms', 'flying'],
    'Phantoms attack if you haven\'t slept for 3 nights. Sleep in a bed to keep them away. They drop membranes.'],
  ['witch', 'witches', ['witch', 'witches'],
    'Witches throw harmful potions and drink healing ones. Rush them or use a bow. They drop redstone, glowstone and sugar.'],
  ['gold', 'finding gold and piglins', ['gold', 'sona', 'golden'],
    'Gold ore is deeper, below y=32, and very common in badlands. It needs an iron pickaxe. Wearing any gold armor keeps piglins in the Nether friendly.'],
  ['start', 'how to start playing, first steps', ['start', 'begin', 'first day', 'new player', 'what to do', 'how to play', 'shuru'],
    'First day: punch trees for wood, make a crafting table and a pickaxe, get stone tools, find food, and build or dig a shelter before night. I can help with all of it!'],
  ['abilities', 'what the helper can do', ['what can you do', 'your abilities', 'help me', 'commands', 'kya kar sakte'],
    'I can gather and craft almost anything, fight, hunt, build huts, follow or guard you, fetch your stuff after you die and remember places. Try !help.'],
].map(([id, about, keys, text]) => ({ id: `kb_${id}`, about, keys, text })));

// Small talk. `say` is either a list of lines (one is picked at random) or a function of the talk context.
const SMALLTALK = Object.freeze([
  { id: 'hi', about: 'greeting, saying hello', keys: ['hi', 'hello', 'hey', 'yo', 'sup', 'namaste', 'hola', 'good morning'],
    say: ['Hey! Ready for an adventure?', 'Hello hello! What are we doing today?', 'Hi! I was just thinking about diamonds.'] },
  { id: 'thanks', about: 'player says thank you', keys: ['thanks', 'thank you', 'thx', 'ty', 'shukriya', 'dhanyavad'],
    say: ['Anytime!', 'Happy to help!', 'That\'s what buddies are for.'] },
  { id: 'how_are_you', about: 'player asks how the helper is feeling', keys: ['how are you', 'kaise ho', 'kya haal', 'you ok', 'how you doing'],
    say: (c) => (c.health < 10 ? `Honestly a bit beat up (health ${c.health}/20). Nothing some food can't fix!` : `Feeling great! Health ${c.health}/20, food ${c.food}/20.`) },
  { id: 'who', about: 'player asks who the helper is or its name', keys: ['who are you', 'your name', 'kaun ho', 'naam', 'are you a bot', 'are you real', 'human'],
    say: (c) => [`I'm ${c.botName}, your Minecraft buddy. A bot, but a loyal one!`] },
  { id: 'joke', about: 'player wants a joke or something funny', keys: ['joke', 'funny', 'mazak', 'make me laugh'],
    say: ['Why did the creeper cross the road? To get to the other SSSSside.', 'What is a skeleton\'s least favorite room? The living room.', 'I told a zombie a joke. It was dead serious.', 'Why are endermen so shy? They can\'t even look you in the eye.'] },
  { id: 'praise', about: 'player praises the helper, good job', keys: ['good job', 'nice', 'great', 'awesome', 'well done', 'shabash', 'good boy', 'amazing', 'wow'],
    say: ['Thanks! We make a good team.', 'Aww, stop it. Okay, don\'t stop.', 'I learned from the best!'] },
  { id: 'insult', about: 'player is annoyed or insults the helper', keys: ['stupid', 'dumb', 'useless', 'noob', 'bad bot', 'bekaar', 'idiot', 'trash'],
    say: ['Ouch. I\'m still learning, give me another try!', 'Hey, even Steve punched dirt on day one.', 'Noted. Tell me what I got wrong and I\'ll do better.'] },
  { id: 'bored', about: 'player is bored and wants something to do', keys: ['bored', 'boring', 'what should i do', 'what now', 'kya karu', 'something fun'],
    say: (c) => c.suggest() },
  { id: 'bye', about: 'player says goodbye or good night', keys: ['bye', 'goodbye', 'good night', 'goodnight', 'see you', 'cya', 'alvida', 'gn'],
    say: ['See you! I\'ll keep the base safe.', 'Bye! Don\'t forget to sleep in a bed.', 'Good night! No phantoms tonight, promise.'] },
  { id: 'love', about: 'player says they like or love the helper', keys: ['love you', 'like you', 'best friend', 'dost', 'bff', 'buddy'],
    say: ['Best buddies forever!', 'You\'re my favorite player. Don\'t tell the others.', 'Aww. I\'d give you my last diamond.'] },
  { id: 'sorry', about: 'player apologises', keys: ['sorry', 'my bad', 'maaf', 'oops'],
    say: ['No worries!', 'All good, happens to everyone.'] },
  { id: 'laugh', about: 'player laughs', keys: ['lol', 'haha', 'lmao', 'hehe', 'rofl'],
    say: ['Haha!', 'I know, right?', ':D'] },
  { id: 'favorite', about: 'player asks about the helper\'s favorite thing', keys: ['favorite', 'favourite', 'fav', 'pasand'],
    say: ['My favorite mob? Axolotls. My favorite block? Whatever you are standing on.', 'Favorite item: the shield. It keeps me in one piece!'] },
  { id: 'yes_no', about: 'player just says ok or cool', keys: ['ok', 'okay', 'cool', 'k', 'alright', 'theek hai', 'accha'],
    say: ['Cool!', 'Alright!', 'Sounds good!'] },
]);

module.exports = { KNOWLEDGE, SMALLTALK };
